### ISSUE TITLE
Question about data normalization

### ISSUE THREAD

**Issue by TArdelean** [NVlabs/edm2#9]
Hello,
Firstly, thanks for the great research and sharing your implementation!
I have a question regarding data normalization when using the sd-vae-ft-mse latent encoder. In your source code you encode_pixels before applying the VAE, which scales the images in [0, 1]. However, as far as I can tell, the SD VAE was trained using a [-1, 1] normalization (https://github.com/huggingface/diffusers/issues/3726#issuecomment-1690905877).
Could you please clarify this discrepancy?

Thanks,
Timotei

**Comment by SonicCodes** [comment]
https://github.com/NVlabs/edm2/blob/38d5a70fe338edc8b3aac4da8a0cefbc4a057fb8/training/encoders.py#L112

here's where the encoding happens to be exact , the OpenAI consistency paper apparently discovered this:
![image](https://github.com/user-attachments/assets/ccc548f2-8b55-470a-8a2b-205084972b71)


@tkarras @TArdelean 

Thanks,

**Comment by TArdelean** [comment]
I see, that clears it up.
Thanks @SonicCodes
